Repository functionguyy/printf, pull requests merged in 2023-08, with the labels that each got.

#3 docs: update README.md
  README.md
Labels: documentation

#20 feat: add header file
  main.h
Labels: documentation

#22 added the custom printf function
  _printf.c
Labels: enhancement

#21 18 feat/format handlers function
  _putchar.c
  get_function.c
  main.h
Labels: enhancement

#24 bug fixed
  get_function.c
Labels: bug

#26 feat: function that produces output according to format specifier c
  print_string_specifier.c
Labels: enhancement

#28 feat: add function that produces output according to format specifier d
  print_decimal_specifier.c
Labels: enhancement

#32 feat: add function that produces output according format specifier s
  print_string_specifier.c
Labels: enhancement

#33 refactor the code
  _printf.c
  _putchar.c
  get_function.c
  main.h
  print_percent_specifier.c
  test/.main.c.swp
  test/_printf.c
  test/_printf.o
  test/_putchar.c
  test/_putchar.o
  test/a.out
  test/get_function.c
  test/get_function.o
  test/lib2.a
  test/main.c
  test/main.h
  test/print_character_specifier.c
  test/print_character_specifier.o
  test/print_decimal_specifier.c
  test/print_decimal_specifier.o
  test/print_percent_specifier.c
  test/print_percent_specifier.o
  test/print_string_specifier.c
  test/print_string_specifier.o
Labels: enhancement

#39 implemented custom specifier S
  get_function.c
  main.h
  print_String_specifier.c
Labels: enhancement

#40 feat: add function that handles custom specifier b
  print_binary_specifier.c
Labels: enhancement

#42 General function to handle number printing in any base
  main.h
  print_number.c
Labels: enhancement

#47 fix: add checks for inconsistent values
  print_binary_specifier.c
Labels: bug

#49 fix: add pointer to function that handles custom specifier b
  get_function.c
Labels: bug

#54 Write function to handle conversion specifier u
  get_function.c
  main.h
  print_unsigned_int_specifier.c
Labels: enhancement

#55 Write function to handle conversion specifier o
  get_function.c
  main.h
  print_octal_specifier.c
Labels: enhancement
